#!/bin/bash


echo "Hello World"

sqlplus sys/${ORACLE_PASSWORD}@${ORACLE_CONTAINER_DB} as sysdba <<EOF
  ALTER SESSION SET CONTAINER=${ETL_DATABASE_NAME};
  CREATE USER IF NOT EXISTS ${ETL_DATABASE_USERNAME} IDENTIFIED BY ${ETL_DATABASE_PASSWORD} QUOTA UNLIMITED ON USERS;
  GRANT CONNECT,RESOURCE,DBA TO ${ETL_DATABASE_USERNAME};
  GRANT ALL PRIVILEGES TO ${ETL_DATABASE_USERNAME} ;
  EXIT;
EOF
