-- Switch to the Pluggable Database (adjust name based on your image)
--ALTER SESSION SET CONTAINER = ORCLPDB1;
--
---- Create an application user
--CREATE USER sales_etl IDENTIFIED BY "sales_etl";
--GRANT CONNECT, RESOURCE, DBA TO sales_etl;
--ALTER USER sales_etl QUOTA UNLIMITED ON USERS;
--
---- Create a table as the new user
--CREATE TABLE sales_etl.app_config (
--    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    config_key VARCHAR2(50) NOT NULL,
--    config_value VARCHAR2(100)
--);
--
--INSERT INTO dev_user.app_config (config_key, config_value) VALUES ('env', 'development');
--COMMIT;

ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER $APP_USER IDENTIFIED BY $APP_USER_PASSWORD QUOTA UNLIMITED ON USERS;
GRANT CONNECT,RESOURCE,DBA TO $APP_USER;
GRANT ALL PRIVILEGES TO $APP_USER ;